# Generated by Django 3.0.8 on 2020-07-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_remove_department_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='branch.Branch'),
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='branch.Branch'),
        ),
    ]
