# Generated by Django 3.0.8 on 2020-07-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='customers',
            field=models.ManyToManyField(to='customer.Customer'),
        ),
    ]
