# Generated by Django 3.0.8 on 2020-07-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('loan', '0002_loan_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customers',
            field=models.ManyToManyField(related_name='loans', to='customer.Customer'),
        ),
    ]
