# Generated by Django 3.0.8 on 2020-07-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20200713_0232'),
        ('loan', '0003_auto_20200714_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='branch.Branch'),
        ),
    ]
