# Generated by Django 3.0.8 on 2020-07-15 08:56

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20200714_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='CNY', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='CNY', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
