# Generated by Django 3.0.8 on 2020-07-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingaccount',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_checkingaccounts', to='branch.Staff'),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_savingaccounts', to='branch.Staff'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkingaccounts', to='branch.Branch'),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savingaccounts', to='branch.Branch'),
        ),
    ]
