# Generated by Django 3.0.8 on 2020-07-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200713_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingaccount',
            name='currency_type',
        ),
    ]
