# Generated by Django 3.0.8 on 2020-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_savingaccount_currency_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkingaccount',
            constraint=models.UniqueConstraint(fields=('customer', 'branch'), name='unique_branch_customer_checkingaccount'),
        ),
        migrations.AddConstraint(
            model_name='savingaccount',
            constraint=models.UniqueConstraint(fields=('customer', 'branch'), name='unique_branch_customer_savingaccount'),
        ),
    ]
