# Generated by Django 3.0.8 on 2020-07-14 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200714_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='date_opened',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='date_opened',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
